_wandb:
    value:
        cli_version: 0.25.1
        e:
            06h21rzhzmukrmxbwfxi1g4s1y3hau6q:
                args:
                    - --climate
                    - VT
                    - --n_iterations
                    - "500"
                    - --seed
                    - "42"
                    - --save_dir
                    - results/rllib_sac_vt_500_final2
                    - --wandb_name
                    - rllib_sac_vt_500_final2
                cpu_count: 64
                cpu_count_logical: 64
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "53681979392"
                        used: "17508466688"
                email: z5610836@ad.unsw.edu.au
                executable: /root/annex96_common_exercise_1/.venv/bin/python3
                git:
                    commit: 637b9d4ebea592933c2334f5673e7cdd3e36bda2
                    remote: https://github.com/EthanZhu1022/annex96_common_exercise_1.git
                gpu: NVIDIA GeForce RTX 3090
                gpu_count: 4
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10496
                      memoryTotal: "25769803776"
                      name: NVIDIA GeForce RTX 3090
                      uuid: GPU-a6c76469-7815-135b-12cc-77cc7a302e59
                    - architecture: Ampere
                      cudaCores: 10496
                      memoryTotal: "25769803776"
                      name: NVIDIA GeForce RTX 3090
                      uuid: GPU-7b8a6d8d-f62a-8ce8-0c1d-24a425b48ad7
                    - architecture: Ampere
                      cudaCores: 10496
                      memoryTotal: "25769803776"
                      name: NVIDIA GeForce RTX 3090
                      uuid: GPU-c54ab155-900f-c445-45f8-a24eeac7a17d
                    - architecture: Ampere
                      cudaCores: 10496
                      memoryTotal: "25769803776"
                      name: NVIDIA GeForce RTX 3090
                      uuid: GPU-eefc87fc-834d-da97-398f-fad50d9eb631
                host: enormous-vista-9518-77b89f78f5-mhwjb
                memory:
                    total: "540879331328"
                os: Linux-5.15.0-94-generic-x86_64-with-glibc2.39
                program: -m rllib_sac.train
                python: CPython 3.11.13
                root: /root/annex96_common_exercise_1
                startedAt: "2026-04-24T06:50:37.660554Z"
                writerId: 06h21rzhzmukrmxbwfxi1g4s1y3hau6q
        m:
            - "1": episode
              "6":
                - 3
              "7": []
            - "1": test_day
              "6":
                - 3
              "7": []
            - "2": test/daily_secondary_baseline/*
              "5": 2
              "6":
                - 1
              "7": []
            - "2": test/daily_primary/*
              "5": 2
              "6":
                - 1
              "7": []
            - "2": train/*
              "5": 1
              "6":
                - 1
              "7": []
            - "2": test/*
              "5": 1
              "6":
                - 1
              "7": []
            - "2": test/daily/*
              "5": 2
              "6":
                - 1
              "7": []
            - "2": test/daily_secondary/*
              "5": 2
              "6":
                - 1
              "7": []
            - "2": test/daily_baseline/*
              "5": 2
              "6":
                - 1
              "7": []
        python_version: 3.11.13
        t:
            "1":
                - 1
                - 5
                - 30
                - 53
            "2":
                - 1
                - 5
                - 30
                - 53
            "3":
                - 2
                - 7
                - 13
                - 16
                - 41
                - 61
            "4": 3.11.13
            "5": 0.25.1
            "12": 0.25.1
            "13": linux-x86_64
backup_dir:
    value: null
buffer_size:
    value: 100000
climate:
    value: VT
do_test:
    value: true
episode_time_steps:
    value: null
gamma:
    value: 0.99
hidden_sizes:
    value:
        - 256
        - 256
initial_alpha:
    value: 0.2
lr:
    value: 0.0003
n_buildings:
    value: 25
n_iterations:
    value: 500
num_steps_sampled_before_learning_starts:
    value: 1000
num_workers:
    value: 0
rollout_fragment_len:
    value: 200
save_dir:
    value: results/rllib_sac_vt_500_final2
seed:
    value: 42
target_network_update_freq:
    value: 1
tau:
    value: 0.005
test_end_step:
    value: 1415
test_month:
    value: 2
test_start_step:
    value: 744
train_batch_size:
    value: 256
train_end_step:
    value: 743
train_month:
    value: 1
train_start_step:
    value: 0
wandb_name:
    value: rllib_sac_vt_500_final2
wandb_project:
    value: annex96-ce1
